version: '3.9'

services:

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: guestbook
      POSTGRES_PASSWORD: guestbook
      POSTGRES_DB: guestbook
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8081:8080"

  symfony:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/guestbook
