version: '3.9'

services:

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8080

  # TODO: add Apache service

  symfony:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      - database
    ports:
      - 8080:80
    volumes:
      - ./docker/php-fpm:/etc/apache2/sites-enabled
      - ./:/var/www/guestbook
